package controllers

import (
    "booking-data-integration-system/models"
    "encoding/json"
    "github.com/astaxie/beego"
    "time"
)

type BookingController struct {
    beego.Controller
}

// POST /bookings
func (c *BookingController) CreateBooking() {
    var booking models.Booking
    if err := json.Unmarshal(c.Ctx.Input.RequestBody, &booking); err != nil {
        c.Data["json"] = map[string]string{"error": "Invalid payload"}
        c.ServeJSON()
        return
    }

    if booking.Customer == "" || booking.Amount == 0 || booking.Vendor == "" {
        c.Data["json"] = map[string]string{"error": "Missing mandatory fields"}
        c.ServeJSON()
        return
    }

    // Normalize date
    booking.BookingDate = time.Now()

    // Simulate database save
    booking.ID = 1 // In a real app, this would be auto-generated by the DB.

    c.Data["json"] = booking
    c.ServeJSON()
}

// GET /bookings
func (c *BookingController) GetBookings() {
    // Simulated data
    bookings := []models.Booking{
        {ID: 1, Customer: "John Doe", BookingDate: time.Now(), Amount: 100.0, Vendor: "Airline"},
    }
    c.Data["json"] = bookings
    c.ServeJSON()
}

// GET /bookings/:id
func (c *BookingController) GetBookingByID() {
    id := c.Ctx.Input.Param(":id")
    if id != "1" {
        c.Data["json"] = map[string]string{"error": "Booking not found"}
    } else {
        c.Data["json"] = models.Booking{
            ID:          1,
            Customer:    "John Doe",
            BookingDate: time.Now(),
            Amount:      100.0,
            Vendor:      "Airline",
        }
    }
    c.ServeJSON()
}

// DELETE /bookings/:id
func (c *BookingController) DeleteBooking() {
    id := c.Ctx.Input.Param(":id")
    if id != "1" {
        c.Data["json"] = map[string]string{"error": "Booking not found"}
    } else {
        c.Data["json"] = map[string]string{"status": "Booking deleted"}
    }
    c.ServeJSON()
}
